# Generated by Django 4.1.1 on 2022-09-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=5)),
                ('original_link', models.TextField()),
                ('creation_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
