# Generated by Django 4.1.1 on 2022-09-09 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
