# Generated by Django 4.1.1 on 2022-09-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='identifier',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
